using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using Microsoft.Extensions.Logging;
using Uno.Extensions;
using Windows.Foundation;
using Windows.Storage;

#if IS_WINUI
using Microsoft.UI;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Markup;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Imaging;
using Windows.UI;
#else
using Windows.UI;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Markup;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Media.Imaging;
#endif

namespace Uno.Toolkit.UI
{
	public partial class ExtendedSplashScreen
	{
		private const string PackageAppxManifestFileName = "package.appxmanifest";
		private const string AppxManifestFilename = "AppxManifest.xml";
		private const string WasmAppManifestFilename = "appmanifest.js";

		// Embedded into the app assembly by Uno.Resizetizer for every head declaring an UnoSplashScreen,
		// including the Android and iOS heads, which embed no Package.appxmanifest.
		private const string ResizetizerSplashDefinitionResourceName = "UnoSplash.def";

		private static readonly char[] PathSeparators = ['/', '\\'];

		/// <summary>
		/// Gets whether the splash screen is displayed on the current platform, as selected by <see cref="Platforms"/>.
		/// </summary>
		public bool SplashIsEnabled => (Platforms & CurrentPlatform) != 0;

		private static SplashScreenPlatform CurrentPlatform =>
#if WINDOWS
			SplashScreenPlatform.Windows;
#else
			OperatingSystem.IsAndroid() ? SplashScreenPlatform.Android :
			OperatingSystem.IsIOS() ? SplashScreenPlatform.iOS :
			RuntimeInfoHelper.IsBrowser ? SplashScreenPlatform.WebAssembly :
			SplashScreenPlatform.Skia;
#endif

		internal static async Task<FrameworkElement?> GetNativeSplashScreen()
		{
			var splash = RuntimeInfoHelper.IsBrowser
				? await LoadSplashScreenFromWasmManifest()
				: await LoadSplashScreenFromPackageManifest();

			if (splash.ImageUri is null &&
				!RuntimeInfoHelper.IsBrowser &&
				await LoadSplashScreenFromResizetizerDefinition() is { } definition)
			{
				splash = definition;
			}

			return BuildSplashScreen(splash);
		}

		internal static FrameworkElement BuildSplashScreen(SplashScreenInfo splash)
		{
			var image = new Image
			{
				Source = splash.ImageUri is { } imageUri ? new BitmapImage(imageUri) : null,
				Stretch = Stretch.Uniform,
				HorizontalAlignment = HorizontalAlignment.Center,
				VerticalAlignment = VerticalAlignment.Center
			};
			var wrapper = new Grid
			{
				Background = new SolidColorBrush { Color = splash.Background },
				Children = { image },
			};

			if (splash.LogoSize is { } logoSize)
			{
				// Matches the iOS launch storyboard and the pre-Android 12 splash drawable generated by Uno.Resizetizer,
				// which both draw the logo centered at its base size.
				image.Width = logoSize.Width;
				image.Height = logoSize.Height;
			}
			else
			{
				// Position of image aligns with WASM Bootstrapper style for splash image
				// see https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/7d82af66c7dc587f6d1f6b6382860051fc2d92a0/src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css#L21
				image.MaxHeight = 300;
				image.MaxWidth = 620;
				Grid.SetColumn(image, 1);
				wrapper.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
				wrapper.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(18, GridUnitType.Star) });
				wrapper.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
			}

			return wrapper;
		}

		private static async Task<SplashScreenInfo> LoadSplashScreenFromWasmManifest()
		{
			var result = new SplashScreenInfo(ImageUri: null, Background: Colors.Transparent);

			try
			{
				var js = await LoadWasmManifestFile(Assembly.GetEntryAssembly(), WasmAppManifestFilename);
				if (string.IsNullOrWhiteSpace(js))
				{
					return result;
				}

				// note: naive js parsing with string manipulation
				// this may just fail, if we start to use nested object or escaped string containing '}'...
				var startIdx = js!.IndexOf('{') + 1;
				var endIdx = js.LastIndexOf('}') - 1;
				var manifestProps = js.Substring(startIdx, endIdx - startIdx); // Trim "var UnoAppManifest = " from the start of the file so we're left with just the inner of JSON
				var manifest = manifestProps.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
					.Select(x => x.Split(':', 2, StringSplitOptions.TrimEntries))
					.ToDictionarySafe(x => x[0], x => x[1].Trim('\"'));

				return result with
				{
					ImageUri = manifest.TryGetValue("splashScreenImage", out var image) ? new Uri("ms-appx:///" + image) : null,
					Background = manifest.TryGetValue("splashScreenColor", out var color)
						? TryParseColor(color) ?? Colors.Transparent
						: Colors.White,
				};
			}

			catch (Exception e)
			{
				typeof(ExtendedSplashScreen).Log().LogError(0, e, "Error while getting native splash screen.");
			}

			return result;
		}

		private static async Task<SplashScreenInfo> LoadSplashScreenFromPackageManifest()
		{
			var result = new SplashScreenInfo(ImageUri: null, Background: Colors.Transparent);

			try
			{
				var manifest = await LoadAppManifest(Assembly.GetEntryAssembly(), AppxManifestFilename, PackageAppxManifestFileName);
				if (manifest is null)
				{
					return result;
				}

				// https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-visualelements
				var resolver = new XmlNamespaceManager(new NameTable());
				resolver.AddNamespace("win", "http://schemas.microsoft.com/appx/manifest/foundation/windows10"); // cant use "" as default in xpath-select
				resolver.AddNamespace("uap", "http://schemas.microsoft.com/appx/manifest/uap/windows10");
				if (manifest.XPathSelectElement(@"//uap:VisualElements/uap:SplashScreen", resolver) is { } splash)
				{
					return result with
					{
						ImageUri = splash.Attribute("Image") is { } image ? new Uri("ms-appx:///" + image.Value) : null,
						Background = splash.Attribute("BackgroundColor") is { } color
							? TryParseColor(color.Value) ?? Colors.Transparent
							: Colors.White,
					};
				}
			}
			catch (Exception e)
			{
				typeof(ExtendedSplashScreen).Log().LogError(0, e, "Error while getting native splash screen.");
			}

			return result;
		}

		internal static async Task<SplashScreenInfo?> LoadSplashScreenFromResizetizerDefinition()
		{
			try
			{
				foreach (var assembly in GetAppAssemblies())
				{
					using var stream = assembly.GetManifestResourceStream(ResizetizerSplashDefinitionResourceName);
					if (stream is null)
					{
						continue;
					}

					using var reader = new StreamReader(stream);
					return ParseResizetizerDefinition(await reader.ReadLineAsync());
				}
			}
			catch (Exception e)
			{
				typeof(ExtendedSplashScreen).Log().LogError(0, e, "Error while reading the splash screen definition.");
			}

			return null;
		}

		/// <summary>
		/// Parses the single-line splash screen definition written by Uno.Resizetizer,
		/// e.g. <c>File=Assets\Splash\splash_screen.svg;Link=;BaseSize=128,128;Resize=;TintColor=;Color=#FFFFFF;ForegroundScale=</c>.
		/// </summary>
		internal static SplashScreenInfo? ParseResizetizerDefinition(string? definition)
		{
			if (string.IsNullOrWhiteSpace(definition))
			{
				return null;
			}

			string? file = null, baseSize = null, color = null;
			foreach (var entry in definition.Split(';', StringSplitOptions.RemoveEmptyEntries))
			{
				var separatorIndex = entry.IndexOf('=');
				if (separatorIndex <= 0)
				{
					continue;
				}

				var value = entry.Substring(separatorIndex + 1).Trim();
				switch (entry.Substring(0, separatorIndex).Trim())
				{
					case "File":
						file = value;
						break;
					case "BaseSize":
						baseSize = value;
						break;
					case "Color":
						color = value;
						break;
				}
			}

			if (string.IsNullOrEmpty(file))
			{
				return null;
			}

			// Resizetizer publishes the splash image at the app root whatever folder its source is in (Link is ignored),
			// rasterizing vector sources to png. The scale-qualified variants are resolved by the image loading.
			var fileName = file.Substring(file.LastIndexOfAny(PathSeparators) + 1);
			var extension = Path.GetExtension(fileName);
			if (string.Equals(extension, ".svg", StringComparison.OrdinalIgnoreCase))
			{
				extension = ".png";
			}

			return new SplashScreenInfo(
				ImageUri: new Uri("ms-appx:///" + Path.GetFileNameWithoutExtension(fileName) + extension),
				Background: string.IsNullOrEmpty(color) ? Colors.White : TryParseColor(color) ?? Colors.Transparent,
				LogoSize: TryParseSize(baseSize));
		}

		// There is no managed entry assembly on Android, and the Application may be declared outside of the head assembly.
		private static Assembly[] GetAppAssemblies() =>
			new[] { Assembly.GetEntryAssembly(), Application.Current?.GetType().Assembly }
				.OfType<Assembly>()
				.Distinct()
				.ToArray();

		private static async Task<string?> LoadWasmManifestFile(Assembly? entry, string manifestFile)
		{
			try
			{
				var storageFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///{manifestFile}"));
				return await FileIO.ReadTextAsync(storageFile);
			}
			catch
			{
				var res = entry?.GetManifestResourceNames()?.FirstOrDefault(x => x.ToLower().Contains(manifestFile, StringComparison.InvariantCultureIgnoreCase));
				if (string.IsNullOrWhiteSpace(res))
				{
					return null;
				}

				var packageStream = entry?.GetManifestResourceStream(res);
				if (packageStream is not null)
				{
					using var streamReader = new StreamReader(packageStream);
					return await streamReader.ReadToEndAsync();
				}
			}

			return null;
		}

		private static async Task<XDocument?> LoadAppManifest(Assembly? entry, params string[] manifestFiles)
		{
			foreach (var file in manifestFiles)
			{
				if ((await LoadManifestFromPackageFile(entry, file) ?? LoadManifestFromEmbeddedFile(entry, file)) is { } doc)
				{
					return doc;
				}
			}
			return default;
		}

		private static async Task<XDocument?> LoadManifestFromPackageFile(Assembly? entry, string manifestFile)
		{
			try
			{
				typeof(ExtendedSplashScreen).Log().LogTrace($"Attempting to load manifest `{manifestFile}` from file packaged with application.");
				var filePath = await ApplicationPathFromFileName(entry, manifestFile);
				if (!string.IsNullOrWhiteSpace(filePath))
				{
					typeof(ExtendedSplashScreen).Log().LogTrace($"Full path to {manifestFile} is {filePath}.");
					return XDocument.Load(filePath, LoadOptions.None);
				}
			}
			catch (Exception docError)
			{
				typeof(ExtendedSplashScreen).Log().LogDebug($"The manifest `{manifestFile}` exists as a packaged file but could not be loaded to XDocument: {docError}.");
			}

			return default;
		}

		private static XDocument? LoadManifestFromEmbeddedFile(Assembly? entry, string manifestFile)
		{
			typeof(ExtendedSplashScreen).Log().LogTrace($"Attempting to load manifest from embedded resource `{manifestFile}` within the {entry?.GetName().Name} assembly.");
			// Check EndsWith because the file may have a prefix based on the project and folder the file was sourced from
			var res = entry?.GetManifestResourceNames()?.FirstOrDefault(x => x.ToLower().EndsWith(manifestFile));
			if (!string.IsNullOrWhiteSpace(res))
			{
				var packageStream = entry!.GetManifestResourceStream(res!);

				if (packageStream is not null)
				{
					try
					{
						return XDocument.Load(packageStream, LoadOptions.None);
					}
					catch (Exception docError)
					{
						typeof(ExtendedSplashScreen).Log().LogTrace($"The manifest `{manifestFile}` exists as a packaged file but could not be loaded to XDocument: {docError}.");
					}
				}
			}

			return default;
		}

		private static async Task<string> ApplicationPathFromFileName(Assembly? entry, string fileName)
		{
			// Note: We attempt to resolve based on the assembly first because it doesn't throw an exception if the file doesn't exist
			// whereas StorageFile.GetFileFromApplicationUriAsync will throw an exception if the file doesn't exist.
			var filePath = string.Empty;
#pragma warning disable SYSLIB0044 // Type or member is obsolete
			var codebase = entry?.GetName().CodeBase;
#pragma warning restore SYSLIB0044 // Type or member is obsolete
			if (codebase is not null)
			{
#if WINDOWS
				// Need to unescape the path to get the actual path
				// `codebase` returns a string with 'file:\' as a prefix which prevents the file from being found
				UriBuilder uri = new UriBuilder(codebase);
				codebase = Uri.UnescapeDataString(uri.Path);
#endif
				var manifestPath = Path.Combine(Path.GetDirectoryName(codebase) ?? string.Empty, fileName);
				if (File.Exists(manifestPath))
				{
					filePath = manifestPath;
				}
			}

			if (string.IsNullOrWhiteSpace(filePath))
			{
				try
				{
					var storageFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///{fileName}"));
					filePath = storageFile.Path;
				}
				catch
				{
					typeof(ExtendedSplashScreen).Log().LogTrace($"Unable to load application StorageFile for {fileName}.");
				}
			}

			return filePath;
		}

		private static Color? TryParseColor(string value)
		{
			try
			{
				return (Color)XamlBindingHelper.ConvertValue(typeof(Color), value);
			}
			catch (Exception colorError)
			{
				typeof(ExtendedSplashScreen).Log().LogError(0, colorError, $"Error while converting color: {value}.");
				return null;
			}
		}

		private static Size? TryParseSize(string? value)
		{
			var parts = value?.Split(',', 2);
			if (parts is { Length: > 0 } && int.TryParse(parts[0], NumberStyles.Integer, CultureInfo.InvariantCulture, out var width))
			{
				var height = parts.Length > 1 && int.TryParse(parts[1], NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsedHeight)
					? parsedHeight
					: width;

				return new Size(width, height);
			}

			return null;
		}

		internal readonly record struct SplashScreenInfo(Uri? ImageUri, Color Background, Size? LogoSize = null);
	}
}
