using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Uno.Toolkit.UI;

/// <summary>
/// Reads the <c>appmanifest.js</c> generated by Uno.Wasm.Bootstrap and picks the splash screen values
/// the same way the bootstrapper's HTML loader does, so the hand-off to the XAML copy is seamless.
/// </summary>
internal static class WasmAppManifest
{
	internal const string DefaultLightBackground = "#F3F3F3";
	internal const string DefaultDarkBackground = "#202020";

	internal readonly record struct SplashSelection(string? Image, string Background);

	internal static string GetDefaultBackground(bool isDark) => isDark ? DefaultDarkBackground : DefaultLightBackground;

	/// <summary>
	/// Picks the logo and background the HTML loader shows for the given browser color scheme.
	/// </summary>
	internal static SplashSelection SelectSplash(IReadOnlyDictionary<string, string> manifest, bool isDark)
	{
		var image = isDark && Get(manifest, "splashScreenImageDark") is { } darkImage
			? darkImage
			: Get(manifest, "splashScreenImage");

		var lightBackground = Get(manifest, "lightThemeBackgroundColor");
		var darkBackground = Get(manifest, "darkThemeBackgroundColor");

		string background;
		if (lightBackground is not null || darkBackground is not null)
		{
			// Per-theme keys make the bootstrapper ignore splashScreenColor.
			background = (isDark ? darkBackground : lightBackground) ?? GetDefaultBackground(isDark);
		}
		else if (Get(manifest, "splashScreenColor") is { } color && color != "transparent")
		{
			background = color;
		}
		else
		{
			background = GetDefaultBackground(isDark);
		}

		return new SplashSelection(image, background);
	}

	// Like the bootstrapper, an empty value counts as absent.
	private static string? Get(IReadOnlyDictionary<string, string> manifest, string key)
		=> manifest.TryGetValue(key, out var value) && value.Length > 0 ? value : null;

	/// <summary>
	/// Extracts the string properties of the flat <c>var UnoAppManifest = { key: "value", ... }</c> object.
	/// Lenient: it understands single or double quotes, optional quoted keys, comments and trailing commas,
	/// ignores non-string values and, on malformed input, returns whatever was read before the problem.
	/// </summary>
	internal static Dictionary<string, string> Parse(string? js)
	{
		Dictionary<string, string> result = new(StringComparer.Ordinal);
		if (string.IsNullOrWhiteSpace(js))
		{
			return result;
		}

		var i = js.IndexOf('{');
		if (i < 0)
		{
			return result;
		}

		i++;
		while (true)
		{
			SkipTrivia(js, ref i);
			if (i >= js.Length || js[i] == '}')
			{
				break;
			}

			if (js[i] == ',')
			{
				i++;
				continue;
			}

			var key = IsQuote(js[i]) ? ReadString(js, ref i) : ReadIdentifier(js, ref i);
			if (key is null)
			{
				break;
			}

			SkipTrivia(js, ref i);
			if (i >= js.Length || js[i] != ':')
			{
				break;
			}

			i++;
			SkipTrivia(js, ref i);
			if (i >= js.Length)
			{
				break;
			}

			if (IsQuote(js[i]))
			{
				if (ReadString(js, ref i) is not { } value)
				{
					break;
				}

				result[key] = value;
			}
			else if (!SkipValue(js, ref i))
			{
				break;
			}
		}

		return result;
	}

	private static bool IsQuote(char c) => c is '"' or '\'' or '`';

	private static void SkipTrivia(string js, ref int i)
	{
		while (i < js.Length)
		{
			if (char.IsWhiteSpace(js[i]))
			{
				i++;
			}
			else if (js[i] == '/' && i + 1 < js.Length && js[i + 1] == '/')
			{
				var end = js.IndexOf('\n', i);
				i = end < 0 ? js.Length : end + 1;
			}
			else if (js[i] == '/' && i + 1 < js.Length && js[i + 1] == '*')
			{
				var end = js.IndexOf("*/", i + 2, StringComparison.Ordinal);
				i = end < 0 ? js.Length : end + 2;
			}
			else
			{
				return;
			}
		}
	}

	private static string? ReadIdentifier(string js, ref int i)
	{
		var start = i;
		while (i < js.Length && (char.IsLetterOrDigit(js[i]) || js[i] is '_' or '$' or '-'))
		{
			i++;
		}

		return i > start ? js.Substring(start, i - start) : null;
	}

	// Returns null when the string is unterminated.
	private static string? ReadString(string js, ref int i)
	{
		var quote = js[i++];
		StringBuilder sb = new();
		while (i < js.Length)
		{
			var c = js[i++];
			if (c == quote)
			{
				return sb.ToString();
			}

			if (c != '\\')
			{
				sb.Append(c);
				continue;
			}

			if (i >= js.Length)
			{
				break;
			}

			c = js[i++];
			switch (c)
			{
				case 'n':
					sb.Append('\n');
					break;
				case 'r':
					sb.Append('\r');
					break;
				case 't':
					sb.Append('\t');
					break;
				case 'b':
					sb.Append('\b');
					break;
				case 'f':
					sb.Append('\f');
					break;
				case 'v':
					sb.Append('\v');
					break;
				case '0':
					sb.Append('\0');
					break;
				case 'u' when TryReadHex(js, i, 4, out var unit):
					sb.Append((char)unit);
					i += 4;
					break;
				case 'x' when TryReadHex(js, i, 2, out var unit):
					sb.Append((char)unit);
					i += 2;
					break;
				case '\r' when i < js.Length && js[i] == '\n':
					i++; // line continuation
					break;
				case '\r':
				case '\n':
					break;
				default:
					sb.Append(c);
					break;
			}
		}

		return null;
	}

	private static bool TryReadHex(string js, int start, int length, out int value)
	{
		value = 0;
		return start + length <= js.Length
			&& int.TryParse(js.AsSpan(start, length), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture, out value);
	}

	// Skips a non-string value (number, boolean, null, nested object or array) up to the next top-level ',' or '}'.
	private static bool SkipValue(string js, ref int i)
	{
		var depth = 0;
		while (i < js.Length)
		{
			var c = js[i];
			if (IsQuote(c))
			{
				if (ReadString(js, ref i) is null)
				{
					return false;
				}

				continue;
			}

			if (c == '/' && i + 1 < js.Length && js[i + 1] is '/' or '*')
			{
				SkipTrivia(js, ref i);
				continue;
			}

			if (c is '{' or '[' or '(')
			{
				depth++;
			}
			else if (c is '}' or ']' or ')')
			{
				if (depth == 0)
				{
					return true;
				}

				depth--;
			}
			else if (c == ',' && depth == 0)
			{
				return true;
			}

			i++;
		}

		return false;
	}
}
