global using System.Collections.Immutable;
global using Microsoft.Extensions.Logging;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml;
global using Microsoft.UI;
global using Microsoft.UI.Xaml.Automation;
global using Microsoft.UI.Xaml.Markup;
global using Microsoft.UI.Xaml.Data;
global using Windows.Graphics.Display;
