// Vendored from microsoft/microsoft-ui-reactor @ v0.1.0-preview.13 (c9191b97c40a2e4d6bcbc72df7714184862b4d36), imported 2026-09-04.
// Source: tests/Reactor.Tests/YogaGenerated/YogaRoundingTest.cs -- xUnit->MSTest; DO NOT HAND-EDIT; see Tests/Yoga/README.md.
// SPDX-License-Identifier: MIT -- (c) Microsoft Corporation (C# port); (c) Facebook, Inc. and its affiliates (Yoga).
// Full license text: THIRD-PARTY-NOTICES.md

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Uno.Toolkit.UI;
using Uno.Toolkit.UI.Yoga;

namespace Uno.Toolkit.RuntimeTests.Tests.Yoga;

/// <summary>
/// Ported from yoga/tests/generated/YGRoundingTest.cpp
/// </summary>
[TestClass]
public class YogaRoundingTest
{
    [TestMethod]
    public void Rounding_Flex_Basis_Flex_Grow_Row_Width_Of_100()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(33f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(33f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(34f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(67f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(33f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(67f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(33f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(33f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(34f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(33f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Flex_Basis_Flex_Grow_Row_Prime_Number_Width()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(113f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.FlexGrow = 1f;
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.FlexGrow = 1f;
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(113f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(23f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(23f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(22f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(45f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(23f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        YogaAssert.Equal(68f, root_child3.LayoutX);
        YogaAssert.Equal(0f, root_child3.LayoutY);
        YogaAssert.Equal(22f, root_child3.LayoutWidth);
        YogaAssert.Equal(100f, root_child3.LayoutHeight);
        YogaAssert.Equal(90f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(23f, root_child4.LayoutWidth);
        YogaAssert.Equal(100f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(113f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(90f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(23f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(68f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(22f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(45f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(23f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        YogaAssert.Equal(23f, root_child3.LayoutX);
        YogaAssert.Equal(0f, root_child3.LayoutY);
        YogaAssert.Equal(22f, root_child3.LayoutWidth);
        YogaAssert.Equal(100f, root_child3.LayoutHeight);
        YogaAssert.Equal(0f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(23f, root_child4.LayoutWidth);
        YogaAssert.Equal(100f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Flex_Basis_Flex_Shrink_Row()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(101f);
        root.Height = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexBasis = YogaValue.Point(100f);
        root_child0.FlexShrink = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexBasis = YogaValue.Point(25f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.FlexBasis = YogaValue.Point(25f);
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(101f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(51f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(51f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(25f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(76f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(25f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(101f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(50f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(51f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(25f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(25f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(25f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Flex_Basis_Overrides_Main_Size()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Total_Fractial()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(87.4f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20.3f);
        root_child0.FlexGrow = 0.7f;
        root_child0.FlexBasis = YogaValue.Point(50.3f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1.6f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10.7f);
        root_child2.FlexGrow = 1.1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(87f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0.LayoutWidth);
        YogaAssert.Equal(59f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(59f, root_child1.LayoutY);
        YogaAssert.Equal(87f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(87f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(87f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0.LayoutWidth);
        YogaAssert.Equal(59f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(59f, root_child1.LayoutY);
        YogaAssert.Equal(87f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(87f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Total_Fractial_Nested()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(87.4f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20.3f);
        root_child0.FlexGrow = 0.7f;
        root_child0.FlexBasis = YogaValue.Point(50.3f);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.SetPosition(YogaEdge.Bottom, YogaValue.Point(13.3f));
        root_child0_child0.Height = YogaValue.Point(9.9f);
        root_child0_child0.FlexGrow = 1f;
        root_child0_child0.FlexBasis = YogaValue.Point(0.3f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.SetPosition(YogaEdge.Top, YogaValue.Point(13.3f));
        root_child0_child1.Height = YogaValue.Point(1.1f);
        root_child0_child1.FlexGrow = 4f;
        root_child0_child1.FlexBasis = YogaValue.Point(0.3f);
        root_child0.InsertChild(root_child0_child1, 1);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1.6f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10.7f);
        root_child2.FlexGrow = 1.1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(87f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0.LayoutWidth);
        YogaAssert.Equal(59f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(-13f, root_child0_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(12f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(25f, root_child0_child1.LayoutY);
        YogaAssert.Equal(87f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(47f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(59f, root_child1.LayoutY);
        YogaAssert.Equal(87f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(87f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(87f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0.LayoutWidth);
        YogaAssert.Equal(59f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(-13f, root_child0_child0.LayoutY);
        YogaAssert.Equal(87f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(12f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(25f, root_child0_child1.LayoutY);
        YogaAssert.Equal(87f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(47f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(59f, root_child1.LayoutY);
        YogaAssert.Equal(87f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(87f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Fractial_Input_1()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Fractial_Input_2()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(113.6f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(114f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(65f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(65f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(24f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(25f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(114f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(65f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(65f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(24f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(25f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Fractial_Input_3()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.SetPosition(YogaEdge.Top, YogaValue.Point(0.3f));
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(114f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(65f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(24f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(25f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(114f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(65f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(24f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(25f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Fractial_Input_4()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.SetPosition(YogaEdge.Top, YogaValue.Point(0.7f));
        root.Height = YogaValue.Point(113.4f);
        root.Width = YogaValue.Point(100f);
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(20f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexBasis = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(1f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(1f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(113f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(64f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(64f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(25f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(89f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(24f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Inner_Node_Controversy_Horizontal()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(320f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Height = YogaValue.Point(10f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(320f, root.LayoutWidth);
        YogaAssert.Equal(10f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(107f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(107f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(106f, root_child1.LayoutWidth);
        YogaAssert.Equal(10f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(106f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(213f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(107f, root_child2.LayoutWidth);
        YogaAssert.Equal(10f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(320f, root.LayoutWidth);
        YogaAssert.Equal(10f, root.LayoutHeight);
        YogaAssert.Equal(213f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(107f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(107f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(106f, root_child1.LayoutWidth);
        YogaAssert.Equal(10f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(106f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(107f, root_child2.LayoutWidth);
        YogaAssert.Equal(10f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Inner_Node_Controversy_Vertical()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(320f);
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(10f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(10f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Point(10f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(10f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(10f, root.LayoutWidth);
        YogaAssert.Equal(320f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(10f, root_child0.LayoutWidth);
        YogaAssert.Equal(107f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(107f, root_child1.LayoutY);
        YogaAssert.Equal(10f, root_child1.LayoutWidth);
        YogaAssert.Equal(106f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(10f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(213f, root_child2.LayoutY);
        YogaAssert.Equal(10f, root_child2.LayoutWidth);
        YogaAssert.Equal(107f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(10f, root.LayoutWidth);
        YogaAssert.Equal(320f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(10f, root_child0.LayoutWidth);
        YogaAssert.Equal(107f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(107f, root_child1.LayoutY);
        YogaAssert.Equal(10f, root_child1.LayoutWidth);
        YogaAssert.Equal(106f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(10f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(213f, root_child2.LayoutY);
        YogaAssert.Equal(10f, root_child2.LayoutWidth);
        YogaAssert.Equal(107f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Rounding_Inner_Node_Controversy_Combined()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(640f);
        root.Height = YogaValue.Point(320f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Percent(100f);
        root_child0.FlexGrow = 1f;
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Percent(100f);
        root_child1.FlexGrow = 1f;
        root.InsertChild(root_child1, 1);
        var root_child1_child0 = new YogaNode(config);
        root_child1_child0.Width = YogaValue.Percent(100f);
        root_child1_child0.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child0, 0);
        var root_child1_child1 = new YogaNode(config);
        root_child1_child1.Width = YogaValue.Percent(100f);
        root_child1_child1.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child1, 1);
        var root_child1_child1_child0 = new YogaNode(config);
        root_child1_child1_child0.FlexGrow = 1f;
        root_child1_child1_child0.Width = YogaValue.Percent(100f);
        root_child1_child1.InsertChild(root_child1_child1_child0, 0);
        var root_child1_child2 = new YogaNode(config);
        root_child1_child2.Width = YogaValue.Percent(100f);
        root_child1_child2.FlexGrow = 1f;
        root_child1.InsertChild(root_child1_child2, 2);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Percent(100f);
        root_child2.FlexGrow = 1f;
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(640f, root.LayoutWidth);
        YogaAssert.Equal(320f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(213f, root_child0.LayoutWidth);
        YogaAssert.Equal(320f, root_child0.LayoutHeight);
        YogaAssert.Equal(213f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(214f, root_child1.LayoutWidth);
        YogaAssert.Equal(320f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(214f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(107f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child1.LayoutX);
        YogaAssert.Equal(107f, root_child1_child1.LayoutY);
        YogaAssert.Equal(214f, root_child1_child1.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child1_child0.LayoutY);
        YogaAssert.Equal(214f, root_child1_child1_child0.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child2.LayoutX);
        YogaAssert.Equal(213f, root_child1_child2.LayoutY);
        YogaAssert.Equal(214f, root_child1_child2.LayoutWidth);
        YogaAssert.Equal(107f, root_child1_child2.LayoutHeight);
        YogaAssert.Equal(427f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(213f, root_child2.LayoutWidth);
        YogaAssert.Equal(320f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(640f, root.LayoutWidth);
        YogaAssert.Equal(320f, root.LayoutHeight);
        YogaAssert.Equal(427f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(213f, root_child0.LayoutWidth);
        YogaAssert.Equal(320f, root_child0.LayoutHeight);
        YogaAssert.Equal(213f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(214f, root_child1.LayoutWidth);
        YogaAssert.Equal(320f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child0.LayoutY);
        YogaAssert.Equal(214f, root_child1_child0.LayoutWidth);
        YogaAssert.Equal(107f, root_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child1.LayoutX);
        YogaAssert.Equal(107f, root_child1_child1.LayoutY);
        YogaAssert.Equal(214f, root_child1_child1.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child1_child1_child0.LayoutY);
        YogaAssert.Equal(214f, root_child1_child1_child0.LayoutWidth);
        YogaAssert.Equal(106f, root_child1_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1_child2.LayoutX);
        YogaAssert.Equal(213f, root_child1_child2.LayoutY);
        YogaAssert.Equal(214f, root_child1_child2.LayoutWidth);
        YogaAssert.Equal(107f, root_child1_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(213f, root_child2.LayoutWidth);
        YogaAssert.Equal(320f, root_child2.LayoutHeight);
    }

}
