// Vendored from microsoft/microsoft-ui-reactor @ v0.1.0-preview.13 (c9191b97c40a2e4d6bcbc72df7714184862b4d36), imported 2026-09-04.
// Source: tests/Reactor.Tests/YogaGenerated/YogaAndroidNewsFeed.cs -- xUnit->MSTest; DO NOT HAND-EDIT; see Tests/Yoga/README.md.
// SPDX-License-Identifier: MIT -- (c) Microsoft Corporation (C# port); (c) Facebook, Inc. and its affiliates (Yoga).
// Full license text: THIRD-PARTY-NOTICES.md

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Uno.Toolkit.UI;
using Uno.Toolkit.UI.Yoga;

namespace Uno.Toolkit.RuntimeTests.Tests.Yoga;

/// <summary>
/// Ported from yoga/tests/generated/YGAndroidNewsFeed.cpp
/// </summary>
[TestClass]
public class YogaAndroidNewsFeed
{
    [TestMethod]
    public void Android_News_Feed()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.AlignContent = FlexAlign.Stretch;
        root.Width = YogaValue.Point(1080f);
        var root_child0 = new YogaNode(config);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0.AlignItems = FlexAlign.FlexStart;
        root_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0.SetMargin(YogaEdge.Top, YogaValue.Point(24f));
        root_child0_child0_child0_child0.SetMargin(YogaEdge.Start, YogaValue.Point(36f));
        root_child0_child0_child0.InsertChild(root_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child0_child0.Width = YogaValue.Point(120f);
        root_child0_child0_child0_child0_child0_child0.Height = YogaValue.Point(120f);
        root_child0_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child0_child0, 0);
        var root_child0_child0_child0_child0_child1 = new YogaNode(config);
        root_child0_child0_child0_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.SetMargin(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Left, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Top, YogaValue.Point(21f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child0_child0_child1.SetPadding(YogaEdge.Bottom, YogaValue.Point(18f));
        root_child0_child0_child0_child0.InsertChild(root_child0_child0_child0_child0_child1, 1);
        var root_child0_child0_child0_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child0_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child0_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1_child0.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.InsertChild(root_child0_child0_child0_child0_child1_child0, 0);
        var root_child0_child0_child0_child0_child1_child1 = new YogaNode(config);
        root_child0_child0_child0_child0_child1_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child0_child0_child1_child1.FlexShrink = 1f;
        root_child0_child0_child0_child0_child1.InsertChild(root_child0_child0_child0_child0_child1_child1, 1);
        var root_child0_child0_child1 = new YogaNode(config);
        root_child0_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0.InsertChild(root_child0_child0_child1, 1);
        var root_child0_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0.AlignItems = FlexAlign.FlexStart;
        root_child0_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0.SetMargin(YogaEdge.Top, YogaValue.Point(24f));
        root_child0_child0_child1_child0.SetMargin(YogaEdge.Start, YogaValue.Point(174f));
        root_child0_child0_child1.InsertChild(root_child0_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0.InsertChild(root_child0_child0_child1_child0_child0, 0);
        var root_child0_child0_child1_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child0_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child0_child0.Width = YogaValue.Point(72f);
        root_child0_child0_child1_child0_child0_child0.Height = YogaValue.Point(72f);
        root_child0_child0_child1_child0_child0.InsertChild(root_child0_child0_child1_child0_child0_child0, 0);
        var root_child0_child0_child1_child0_child1 = new YogaNode(config);
        root_child0_child0_child1_child0_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.SetMargin(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Left, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Top, YogaValue.Point(21f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Right, YogaValue.Point(36f));
        root_child0_child0_child1_child0_child1.SetPadding(YogaEdge.Bottom, YogaValue.Point(18f));
        root_child0_child0_child1_child0.InsertChild(root_child0_child0_child1_child0_child1, 1);
        var root_child0_child0_child1_child0_child1_child0 = new YogaNode(config);
        root_child0_child0_child1_child0_child1_child0.FlexDirection = FlexDirection.Row;
        root_child0_child0_child1_child0_child1_child0.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1_child0.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.InsertChild(root_child0_child0_child1_child0_child1_child0, 0);
        var root_child0_child0_child1_child0_child1_child1 = new YogaNode(config);
        root_child0_child0_child1_child0_child1_child1.AlignContent = FlexAlign.Stretch;
        root_child0_child0_child1_child0_child1_child1.FlexShrink = 1f;
        root_child0_child0_child1_child0_child1.InsertChild(root_child0_child0_child1_child0_child1_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(1080f, root.LayoutWidth);
        YogaAssert.Equal(240f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0.LayoutWidth);
        YogaAssert.Equal(240f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(240f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(144f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(24f, root_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(1044f, root_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child1.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child0_child0_child1.LayoutWidth);
        YogaAssert.Equal(39f, root_child0_child0_child0_child0_child1.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child0_child0_child1_child0.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child0_child0_child1_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child0_child0_child1_child1.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child0_child0_child1_child1.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1.LayoutX);
        YogaAssert.Equal(144f, root_child0_child0_child1.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0_child1.LayoutWidth);
        YogaAssert.Equal(96f, root_child0_child0_child1.LayoutHeight);
        YogaAssert.Equal(174f, root_child0_child0_child1_child0.LayoutX);
        YogaAssert.Equal(24f, root_child0_child0_child1_child0.LayoutY);
        YogaAssert.Equal(906f, root_child0_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutWidth);
        YogaAssert.Equal(39f, root_child0_child0_child1_child0_child1.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child1_child0_child1_child0.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child1_child0_child1_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child1_child0_child1_child1.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child1_child0_child1_child1.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(1080f, root.LayoutWidth);
        YogaAssert.Equal(240f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0.LayoutWidth);
        YogaAssert.Equal(240f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(240f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(144f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(24f, root_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(1044f, root_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(924f, root_child0_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child0_child0.LayoutY);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(120f, root_child0_child0_child0_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(816f, root_child0_child0_child0_child0_child1.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child0_child0_child1.LayoutWidth);
        YogaAssert.Equal(39f, root_child0_child0_child0_child0_child1.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child0_child0_child1_child0.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child0_child0_child1_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child0_child0_child1_child1.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child0_child0_child1_child1.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child0_child0_child1_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1.LayoutX);
        YogaAssert.Equal(144f, root_child0_child0_child1.LayoutY);
        YogaAssert.Equal(1080f, root_child0_child0_child1.LayoutWidth);
        YogaAssert.Equal(96f, root_child0_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0.LayoutX);
        YogaAssert.Equal(24f, root_child0_child0_child1_child0.LayoutY);
        YogaAssert.Equal(906f, root_child0_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(834f, root_child0_child0_child1_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child0_child0.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(726f, root_child0_child0_child1_child0_child1.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1.LayoutY);
        YogaAssert.Equal(72f, root_child0_child0_child1_child0_child1.LayoutWidth);
        YogaAssert.Equal(39f, root_child0_child0_child1_child0_child1.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child1_child0_child1_child0.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child1_child0_child1_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child0.LayoutHeight);
        YogaAssert.Equal(36f, root_child0_child0_child1_child0_child1_child1.LayoutX);
        YogaAssert.Equal(21f, root_child0_child0_child1_child0_child1_child1.LayoutY);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child0_child0_child1_child0_child1_child1.LayoutHeight);
    }

}
