// Vendored from microsoft/microsoft-ui-reactor @ v0.1.0-preview.13 (c9191b97c40a2e4d6bcbc72df7714184862b4d36), imported 2026-09-04.
// Source: tests/Reactor.Tests/YogaGenerated/YogaFlexWrapTest.cs -- xUnit->MSTest; DO NOT HAND-EDIT; see Tests/Yoga/README.md.
// SPDX-License-Identifier: MIT -- (c) Microsoft Corporation (C# port); (c) Facebook, Inc. and its affiliates (Yoga).
// Full license text: THIRD-PARTY-NOTICES.md

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Uno.Toolkit.UI;
using Uno.Toolkit.UI.Yoga;

namespace Uno.Toolkit.RuntimeTests.Tests.Yoga;

/// <summary>
/// Ported from yoga/tests/generated/YGFlexWrapTest.cpp
/// </summary>
[TestClass]
public class YogaFlexWrapTest
{
    [TestMethod]
    [Ignore("Skipped in upstream Yoga (GTEST_SKIP)")]
    public void Wrap_Column()
    {
        // TODO: GTEST_SKIP();
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(100f);
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(30f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(30f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(30f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(30f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(30f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(30f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(60f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(30f, root_child3.LayoutX);
        YogaAssert.Equal(0f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(30f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(30f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(30f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(60f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(-30f, root_child3.LayoutX);
        YogaAssert.Equal(0f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Row()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(30f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(30f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(30f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(30f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(30f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(30f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Row_Align_Items_Flex_End()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        root.AlignItems = FlexAlign.FlexEnd;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(30f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(20f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(10f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(20f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(10f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Row_Align_Items_Center()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        root.AlignItems = FlexAlign.Center;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(30f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(10f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(5f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(60f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(10f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(5f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(0f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(30f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(30f, root_child3.LayoutHeight);
    }

    [TestMethod]
    public void Flex_Wrap_Children_With_Min_Main_Overriding_Flex_Basis()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexWrap = FlexWrap.Wrap;
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexBasis = YogaValue.Point(50f);
        root_child0.Height = YogaValue.Point(50f);
        root_child0.MinWidth = YogaValue.Point(55f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.FlexBasis = YogaValue.Point(50f);
        root_child1.Height = YogaValue.Point(50f);
        root_child1.MinWidth = YogaValue.Point(55f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(55f, root_child0.LayoutWidth);
        YogaAssert.Equal(50f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(50f, root_child1.LayoutY);
        YogaAssert.Equal(55f, root_child1.LayoutWidth);
        YogaAssert.Equal(50f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(45f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(55f, root_child0.LayoutWidth);
        YogaAssert.Equal(50f, root_child0.LayoutHeight);
        YogaAssert.Equal(45f, root_child1.LayoutX);
        YogaAssert.Equal(50f, root_child1.LayoutY);
        YogaAssert.Equal(55f, root_child1.LayoutWidth);
        YogaAssert.Equal(50f, root_child1.LayoutHeight);
    }

    [TestMethod]
    public void Flex_Wrap_Wrap_To_Child_Height()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.AlignItems = FlexAlign.FlexStart;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(100f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.Height = YogaValue.Point(100f);
        root_child0_child0_child0.Width = YogaValue.Point(100f);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(100f);
        root_child1.Height = YogaValue.Point(100f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(100f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(100f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(100f, root_child1.LayoutY);
        YogaAssert.Equal(100f, root_child1.LayoutWidth);
        YogaAssert.Equal(100f, root_child1.LayoutHeight);
    }

    [TestMethod]
    public void Flex_Wrap_Align_Stretch_Fits_One_Row()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(150f);
        root.Height = YogaValue.Point(100f);
        root.FlexWrap = FlexWrap.Wrap;
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(50f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(50f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(150f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(50f, root_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0.LayoutHeight);
        YogaAssert.Equal(50f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(50f, root_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(150f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(100f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(50f, root_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0.LayoutHeight);
        YogaAssert.Equal(50f, root_child1.LayoutX);
        YogaAssert.Equal(0f, root_child1.LayoutY);
        YogaAssert.Equal(50f, root_child1.LayoutWidth);
        YogaAssert.Equal(0f, root_child1.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Row_Align_Content_Flex_Start()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.WrapReverse;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(30f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(40f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Row_Align_Content_Center()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.WrapReverse;
        root.AlignContent = FlexAlign.Center;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(30f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(40f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Row_Single_Line_Different_Size()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(300f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.WrapReverse;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(300f, root.LayoutWidth);
        YogaAssert.Equal(50f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(40f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(30f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(20f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(90f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(120f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(300f, root.LayoutWidth);
        YogaAssert.Equal(50f, root.LayoutHeight);
        YogaAssert.Equal(270f, root_child0.LayoutX);
        YogaAssert.Equal(40f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(240f, root_child1.LayoutX);
        YogaAssert.Equal(30f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(210f, root_child2.LayoutX);
        YogaAssert.Equal(20f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(180f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(150f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Row_Align_Content_Stretch()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.WrapReverse;
        root.AlignContent = FlexAlign.Stretch;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(30f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(40f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Row_Align_Content_Space_Around()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(100f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.WrapReverse;
        root.AlignContent = FlexAlign.SpaceAround;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(60f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(30f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(100f, root.LayoutWidth);
        YogaAssert.Equal(80f, root.LayoutHeight);
        YogaAssert.Equal(70f, root_child0.LayoutX);
        YogaAssert.Equal(70f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(40f, root_child1.LayoutX);
        YogaAssert.Equal(60f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(10f, root_child2.LayoutX);
        YogaAssert.Equal(50f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(70f, root_child3.LayoutX);
        YogaAssert.Equal(10f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(40f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Reverse_Column_Fixed_Size()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(200f);
        root.Height = YogaValue.Point(100f);
        root.FlexWrap = FlexWrap.WrapReverse;
        root.AlignItems = FlexAlign.Center;
        var root_child0 = new YogaNode(config);
        root_child0.Height = YogaValue.Point(10f);
        root_child0.Width = YogaValue.Point(30f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Height = YogaValue.Point(20f);
        root_child1.Width = YogaValue.Point(30f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Height = YogaValue.Point(30f);
        root_child2.Width = YogaValue.Point(30f);
        root.InsertChild(root_child2, 2);
        var root_child3 = new YogaNode(config);
        root_child3.Height = YogaValue.Point(40f);
        root_child3.Width = YogaValue.Point(30f);
        root.InsertChild(root_child3, 3);
        var root_child4 = new YogaNode(config);
        root_child4.Height = YogaValue.Point(50f);
        root_child4.Width = YogaValue.Point(30f);
        root.InsertChild(root_child4, 4);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(170f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(170f, root_child1.LayoutX);
        YogaAssert.Equal(10f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(170f, root_child2.LayoutX);
        YogaAssert.Equal(30f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(170f, root_child3.LayoutX);
        YogaAssert.Equal(60f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(140f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(100f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(30f, root_child0.LayoutWidth);
        YogaAssert.Equal(10f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(10f, root_child1.LayoutY);
        YogaAssert.Equal(30f, root_child1.LayoutWidth);
        YogaAssert.Equal(20f, root_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child2.LayoutX);
        YogaAssert.Equal(30f, root_child2.LayoutY);
        YogaAssert.Equal(30f, root_child2.LayoutWidth);
        YogaAssert.Equal(30f, root_child2.LayoutHeight);
        YogaAssert.Equal(0f, root_child3.LayoutX);
        YogaAssert.Equal(60f, root_child3.LayoutY);
        YogaAssert.Equal(30f, root_child3.LayoutWidth);
        YogaAssert.Equal(40f, root_child3.LayoutHeight);
        YogaAssert.Equal(30f, root_child4.LayoutX);
        YogaAssert.Equal(0f, root_child4.LayoutY);
        YogaAssert.Equal(30f, root_child4.LayoutWidth);
        YogaAssert.Equal(50f, root_child4.LayoutHeight);
    }

    [TestMethod]
    public void Wrapped_Row_Within_Align_Items_Center()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(200f);
        root.Height = YogaValue.Point(200f);
        root.AlignItems = FlexAlign.Center;
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(150f);
        root_child0_child0.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.Width = YogaValue.Point(80f);
        root_child0_child1.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(50f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(120f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
    }

    [TestMethod]
    public void Wrapped_Row_Within_Align_Items_Flex_Start()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(200f);
        root.Height = YogaValue.Point(200f);
        root.AlignItems = FlexAlign.FlexStart;
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(150f);
        root_child0_child0.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.Width = YogaValue.Point(80f);
        root_child0_child1.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(50f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(120f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
    }

    [TestMethod]
    public void Wrapped_Row_Within_Align_Items_Flex_End()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(200f);
        root.Height = YogaValue.Point(200f);
        root.AlignItems = FlexAlign.FlexEnd;
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0_child0.Width = YogaValue.Point(150f);
        root_child0_child0.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.Width = YogaValue.Point(80f);
        root_child0_child1.Height = YogaValue.Point(80f);
        root_child0.InsertChild(root_child0_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(200f, root.LayoutWidth);
        YogaAssert.Equal(200f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(200f, root_child0.LayoutWidth);
        YogaAssert.Equal(160f, root_child0.LayoutHeight);
        YogaAssert.Equal(50f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(150f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(120f, root_child0_child1.LayoutX);
        YogaAssert.Equal(80f, root_child0_child1.LayoutY);
        YogaAssert.Equal(80f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(80f, root_child0_child1.LayoutHeight);
    }

    [TestMethod]
    public void Wrapped_Column_Max_Height()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(500f);
        root.Width = YogaValue.Point(700f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        root.AlignContent = FlexAlign.Center;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(100f);
        root_child0.Height = YogaValue.Point(500f);
        root_child0.MaxHeight = YogaValue.Point(200f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(200f);
        root_child1.Height = YogaValue.Point(200f);
        root_child1.SetMargin(YogaEdge.All, YogaValue.Point(20f));
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(100f);
        root_child2.Height = YogaValue.Point(100f);
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(700f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(250f, root_child0.LayoutX);
        YogaAssert.Equal(30f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(200f, root_child1.LayoutX);
        YogaAssert.Equal(250f, root_child1.LayoutY);
        YogaAssert.Equal(200f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
        YogaAssert.Equal(420f, root_child2.LayoutX);
        YogaAssert.Equal(200f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(700f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(350f, root_child0.LayoutX);
        YogaAssert.Equal(30f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(300f, root_child1.LayoutX);
        YogaAssert.Equal(250f, root_child1.LayoutY);
        YogaAssert.Equal(200f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
        YogaAssert.Equal(180f, root_child2.LayoutX);
        YogaAssert.Equal(200f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Wrapped_Column_Max_Height_Flex()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Height = YogaValue.Point(500f);
        root.Width = YogaValue.Point(700f);
        root.AlignItems = FlexAlign.Center;
        root.JustifyContent = FlexJustify.Center;
        root.AlignContent = FlexAlign.Center;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(100f);
        root_child0.Height = YogaValue.Point(500f);
        root_child0.MaxHeight = YogaValue.Point(200f);
        root_child0.FlexGrow = 1f;
        root_child0.FlexShrink = 1f;
        root_child0.FlexBasis = YogaValue.Percent(0f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(200f);
        root_child1.Height = YogaValue.Point(200f);
        root_child1.SetMargin(YogaEdge.All, YogaValue.Point(20f));
        root_child1.FlexGrow = 1f;
        root_child1.FlexShrink = 1f;
        root_child1.FlexBasis = YogaValue.Percent(0f);
        root.InsertChild(root_child1, 1);
        var root_child2 = new YogaNode(config);
        root_child2.Width = YogaValue.Point(100f);
        root_child2.Height = YogaValue.Point(100f);
        root.InsertChild(root_child2, 2);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(700f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(300f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(180f, root_child0.LayoutHeight);
        YogaAssert.Equal(250f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(200f, root_child1.LayoutWidth);
        YogaAssert.Equal(180f, root_child1.LayoutHeight);
        YogaAssert.Equal(300f, root_child2.LayoutX);
        YogaAssert.Equal(400f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(700f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(300f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(100f, root_child0.LayoutWidth);
        YogaAssert.Equal(180f, root_child0.LayoutHeight);
        YogaAssert.Equal(250f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(200f, root_child1.LayoutWidth);
        YogaAssert.Equal(180f, root_child1.LayoutHeight);
        YogaAssert.Equal(300f, root_child2.LayoutX);
        YogaAssert.Equal(400f, root_child2.LayoutY);
        YogaAssert.Equal(100f, root_child2.LayoutWidth);
        YogaAssert.Equal(100f, root_child2.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Nodes_With_Content_Sizing_Overflowing_Margin()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(500f);
        root.Height = YogaValue.Point(500f);
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root_child0.Width = YogaValue.Point(85f);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.Height = YogaValue.Point(40f);
        root_child0_child0_child0.Width = YogaValue.Point(40f);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.SetMargin(YogaEdge.Right, YogaValue.Point(10f));
        root_child0.InsertChild(root_child0_child1, 1);
        var root_child0_child1_child0 = new YogaNode(config);
        root_child0_child1_child0.Height = YogaValue.Point(40f);
        root_child0_child1_child0.Width = YogaValue.Point(40f);
        root_child0_child1.InsertChild(root_child0_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(85f, root_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(40f, root_child0_child1.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(415f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(85f, root_child0.LayoutWidth);
        YogaAssert.Equal(80f, root_child0.LayoutHeight);
        YogaAssert.Equal(45f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(35f, root_child0_child1.LayoutX);
        YogaAssert.Equal(40f, root_child0_child1.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Nodes_With_Content_Sizing_Margin_Cross()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(500f);
        root.Height = YogaValue.Point(500f);
        var root_child0 = new YogaNode(config);
        root_child0.FlexDirection = FlexDirection.Row;
        root_child0.FlexWrap = FlexWrap.Wrap;
        root_child0.Width = YogaValue.Point(70f);
        root.InsertChild(root_child0, 0);
        var root_child0_child0 = new YogaNode(config);
        root_child0.InsertChild(root_child0_child0, 0);
        var root_child0_child0_child0 = new YogaNode(config);
        root_child0_child0_child0.Height = YogaValue.Point(40f);
        root_child0_child0_child0.Width = YogaValue.Point(40f);
        root_child0_child0.InsertChild(root_child0_child0_child0, 0);
        var root_child0_child1 = new YogaNode(config);
        root_child0_child1.SetMargin(YogaEdge.Top, YogaValue.Point(10f));
        root_child0.InsertChild(root_child0_child1, 1);
        var root_child0_child1_child0 = new YogaNode(config);
        root_child0_child1_child0.Height = YogaValue.Point(40f);
        root_child0_child1_child0.Width = YogaValue.Point(40f);
        root_child0_child1.InsertChild(root_child0_child1_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(70f, root_child0.LayoutWidth);
        YogaAssert.Equal(90f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1.LayoutX);
        YogaAssert.Equal(50f, root_child0_child1.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(430f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(70f, root_child0.LayoutWidth);
        YogaAssert.Equal(90f, root_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child0_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child0_child0.LayoutHeight);
        YogaAssert.Equal(30f, root_child0_child1.LayoutX);
        YogaAssert.Equal(50f, root_child0_child1.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1.LayoutHeight);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0_child1_child0.LayoutY);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutWidth);
        YogaAssert.Equal(40f, root_child0_child1_child0.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_With_Min_Cross_Axis()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(500f);
        root.MinHeight = YogaValue.Point(500f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(400f);
        root_child0.Height = YogaValue.Point(200f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(400f);
        root_child1.Height = YogaValue.Point(200f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(400f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(400f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(500f, root.LayoutHeight);
        YogaAssert.Equal(100f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(400f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(100f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(400f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_With_Max_Cross_Axis()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.Width = YogaValue.Point(500f);
        root.MaxHeight = YogaValue.Point(500f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.Width = YogaValue.Point(400f);
        root_child0.Height = YogaValue.Point(200f);
        root.InsertChild(root_child0, 0);
        var root_child1 = new YogaNode(config);
        root_child1.Width = YogaValue.Point(400f);
        root_child1.Height = YogaValue.Point(200f);
        root.InsertChild(root_child1, 1);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(400f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(0f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(400f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(500f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(100f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(400f, root_child0.LayoutWidth);
        YogaAssert.Equal(200f, root_child0.LayoutHeight);
        YogaAssert.Equal(100f, root_child1.LayoutX);
        YogaAssert.Equal(200f, root_child1.LayoutY);
        YogaAssert.Equal(400f, root_child1.LayoutWidth);
        YogaAssert.Equal(200f, root_child1.LayoutHeight);
    }

    [TestMethod]
    public void Nowrap_Expands_Flexline_Box_To_Min_Cross()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.MinHeight = YogaValue.Point(400f);
        root.FlexDirection = FlexDirection.Row;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root_child0.FlexShrink = 1f;
        root_child0.FlexBasis = YogaValue.Percent(0f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(0f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0.LayoutWidth);
        YogaAssert.Equal(400f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(0f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0.LayoutWidth);
        YogaAssert.Equal(400f, root_child0.LayoutHeight);
    }

    [TestMethod]
    public void Wrap_Does_Not_Impose_Min_Cross_Onto_Single_Flexline()
    {
        var config = new YogaConfig();
        var root = new YogaNode(config);
        root.PositionType = FlexPositionType.Absolute;
        root.MinHeight = YogaValue.Point(400f);
        root.FlexDirection = FlexDirection.Row;
        root.FlexWrap = FlexWrap.Wrap;
        var root_child0 = new YogaNode(config);
        root_child0.FlexGrow = 1f;
        root_child0.FlexShrink = 1f;
        root_child0.FlexBasis = YogaValue.Percent(0f);
        root.InsertChild(root_child0, 0);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.LeftToRight);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(0f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0.LayoutHeight);
        root.CalculateLayout(float.NaN, float.NaN, FlexLayoutDirection.RightToLeft);
        YogaAssert.Equal(0f, root.LayoutX);
        YogaAssert.Equal(0f, root.LayoutY);
        YogaAssert.Equal(0f, root.LayoutWidth);
        YogaAssert.Equal(400f, root.LayoutHeight);
        YogaAssert.Equal(0f, root_child0.LayoutX);
        YogaAssert.Equal(0f, root_child0.LayoutY);
        YogaAssert.Equal(0f, root_child0.LayoutWidth);
        YogaAssert.Equal(0f, root_child0.LayoutHeight);
    }

}
